[2019-02-16 12:43:52.099525] == Executing C:\dsa\dart-sdk\bin\dart.exe with arguments [bin/run.dart, --name, MongoDB, --log, info, --old, false, --broker, http://127.0.0.1:50394/conn, --token, pMKOvvGjtpaOnLMi63vQlj8APYJdhv9FbL4vCmpDxrSnM889] (pid: 9428) ==
[2019-02-16 12:43:54.598775] [INFO][DSA] Connecting to http://127.0.0.1:50394/conn
[2019-02-16 12:43:54.746687] [INFO][DSA] Connected
[2019-02-16 12:44:33.281183] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:44:33.281183] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:44:33.281183] 
[2019-02-16 12:44:33.281183] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62183
[2019-02-16 12:44:33.281183] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:44:33.281183] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:44:33.281183] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:44:33.281183] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:44:33.282165] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:44:39.286173] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:44:39.286173] 
[2019-02-16 12:44:39.286173] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62186
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:44:39.286173] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:44:45.290651] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:44:45.290651] 
[2019-02-16 12:44:45.290651] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62187
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:44:45.290651] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:44:51.302436] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:44:51.302436] 
[2019-02-16 12:44:51.302436] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62188
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:44:51.302436] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:44:57.307285] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:44:57.307285] 
[2019-02-16 12:44:57.307285] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62194
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:44:57.307285] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:44:57.308284] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:44:57.308284] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:44:57.308284] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:44:57.308284] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:03.315910] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:03.315910] 
[2019-02-16 12:45:03.315910] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62200
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:03.315910] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:03.316909] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:03.316909] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:09.320206] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:09.321206] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:09.321206] 
[2019-02-16 12:45:09.321206] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62219
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:09.321206] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:15.325940] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:15.325940] 
[2019-02-16 12:45:15.325940] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62245
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:15.325940] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:21.329811] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:21.329811] 
[2019-02-16 12:45:21.329811] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62255
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:21.329811] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:27.333894] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:27.333894] 
[2019-02-16 12:45:27.333894] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62258
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:27.333894] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:33.338575] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:33.338575] 
[2019-02-16 12:45:33.338575] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62259
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:33.338575] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:39.343464] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:39.343464] 
[2019-02-16 12:45:39.343464] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62265
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:39.343464] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:45.352903] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:45.352903] 
[2019-02-16 12:45:45.352903] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62267
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:45.352903] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:51.359819] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:51.359819] 
[2019-02-16 12:45:51.359819] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62271
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:51.359819] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:51.362818] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:51.362818] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:51.362818] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:51.362818] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:51.362818] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:45:57.364313] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:45:57.365328] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:45:57.365328] 
[2019-02-16 12:45:57.365328] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62276
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:45:57.365328] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:03.374454] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:03.374454] 
[2019-02-16 12:46:03.374454] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62293
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:03.374454] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:09.380922] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:09.381920] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:09.381920] 
[2019-02-16 12:46:09.381920] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62302
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:09.381920] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:15.388445] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:15.388445] 
[2019-02-16 12:46:15.388445] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62319
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:15.388445] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:21.391058] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:21.392058] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:21.392058] 
[2019-02-16 12:46:21.392058] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62321
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:21.392058] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:27.397890] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:27.397890] 
[2019-02-16 12:46:27.397890] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62326
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:27.397890] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:27.398889] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:27.398889] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:27.398889] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:33.403094] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:33.403094] 
[2019-02-16 12:46:33.403094] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62327
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:33.403094] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:39.408980] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:39.408980] 
[2019-02-16 12:46:39.408980] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62338
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:39.408980] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:45.415742] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:45.415742] 
[2019-02-16 12:46:45.415742] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62341
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:45.415742] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:51.429768] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:51.429768] 
[2019-02-16 12:46:51.429768] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62346
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:51.429768] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:46:57.434463] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:46:57.434463] 
[2019-02-16 12:46:57.434463] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62350
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:46:57.434463] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:03.439015] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:03.439015] 
[2019-02-16 12:47:03.439015] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62351
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:03.439015] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:09.444710] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:09.444710] 
[2019-02-16 12:47:09.444710] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62354
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:09.444710] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:15.449086] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:15.449086] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:15.449086] 
[2019-02-16 12:47:15.450086] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62356
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #11     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:15.450086] [SEVERE][DSA] #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:21.244646] == Exited with status 1 ==
[2019-02-16 12:47:21.244646] == Exited with status 1 ==
[2019-02-16 12:47:21.396559] == Executing C:\dsa\dart-sdk\bin\dart.exe with arguments [bin/run.dart, --name, MongoDB, --log, info, --old, false, --broker, http://127.0.0.1:50394/conn, --token, pMKOvvGjtpaOnLMi63vQlj8APYJdhv9FbL4vCmpDxrSnM889] (pid: 21372) ==
[2019-02-16 12:47:21.984221] [INFO][DSA] Connecting to http://127.0.0.1:50394/conn
[2019-02-16 12:47:22.161119] [INFO][DSA] Connected
[2019-02-16 12:47:23.040414] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:23.040414] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:23.040414] 
[2019-02-16 12:47:23.040414] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62360
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:23.040414] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:29.047792] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:29.047792] 
[2019-02-16 12:47:29.047792] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62365
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:29.047792] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:35.053366] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:35.053366] 
[2019-02-16 12:47:35.053366] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62371
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:35.053366] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:41.057911] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:41.057911] 
[2019-02-16 12:47:41.057911] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62418
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:41.057911] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:47.064224] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:47.064224] 
[2019-02-16 12:47:47.064224] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62424
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:47.064224] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:53.070128] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:53.070128] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:53.070128] 
[2019-02-16 12:47:53.070128] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62428
[2019-02-16 12:47:53.070128] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:53.071128] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:53.071128] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:53.071128] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:53.071128] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:53.071128] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:53.071128] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:53.072127] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:47:59.078724] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:47:59.078724] 
[2019-02-16 12:47:59.078724] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62430
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:47:59.078724] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:05.082104] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:05.083104] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:05.083104] 
[2019-02-16 12:48:05.083104] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62433
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:05.083104] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:11.086881] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:11.086881] 
[2019-02-16 12:48:11.086881] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62437
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:11.086881] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:17.091796] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:17.092795] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:17.092795] 
[2019-02-16 12:48:17.092795] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62438
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:17.092795] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:23.099517] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:23.099517] 
[2019-02-16 12:48:23.099517] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62441
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:23.099517] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:29.103304] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:29.103304] 
[2019-02-16 12:48:29.103304] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62443
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:29.103304] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] Failed to connect to database for /t
[2019-02-16 12:48:34.050583] [SEVERE][DSA] MongoDart Error: Invalid scheme in uri: /downstream/Weather/Aguascalientes-4019233/Temperature 
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #0      Db._parseUri (package:mongo_dart/src/database/db.dart:150:7)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:248:42)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #2      List.forEach (dart:core-patch/growable_array.dart:254)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:247:16)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #4      Future.Future.sync (dart:async/future.dart:168)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #5      Db.open (package:mongo_dart/src/database/db.dart:238:16)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #6      MongoHistorianAdapter.getDatabase.<getDatabase_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///C:/dsa/dglux-server/dslinks/MongoDB/bin/run.dart:41:16)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #8      _rootRun (dart:async/zone.dart:946)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #9      _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #10     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #12     _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #13     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #14     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-02-16 12:48:34.050583] [SEVERE][DSA] #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:35.107372] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:35.107372] 
[2019-02-16 12:48:35.107372] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62444
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:35.107372] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:39.054751] [SEVERE][DSA] Failed to connect to database for /t
[2019-02-16 12:48:39.054751] [SEVERE][DSA] MongoDart Error: Invalid scheme in uri: /downstream/Weather/Aguascalientes-4019233/Temperature 
[2019-02-16 12:48:39.054751] [SEVERE][DSA] #0      Db._parseUri (package:mongo_dart/src/database/db.dart:150:7)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:248:42)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #2      List.forEach (dart:core-patch/growable_array.dart:254)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:247:16)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #4      Future.Future.sync (dart:async/future.dart:168)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #5      Db.open (package:mongo_dart/src/database/db.dart:238:16)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #6      MongoHistorianAdapter.getDatabase.<getDatabase_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///C:/dsa/dglux-server/dslinks/MongoDB/bin/run.dart:41:16)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #8      _rootRun (dart:async/zone.dart:946)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #9      _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #10     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #12     _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #13     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #14     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-02-16 12:48:39.060747] [SEVERE][DSA] #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:41.123450] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:41.123450] 
[2019-02-16 12:48:41.123450] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62449
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:41.123450] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] Failed to connect to database for /t
[2019-02-16 12:48:44.059125] [SEVERE][DSA] MongoDart Error: Invalid scheme in uri: /downstream/Weather/Aguascalientes-4019233/Temperature 
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #0      Db._parseUri (package:mongo_dart/src/database/db.dart:150:7)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:248:42)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #2      List.forEach (dart:core-patch/growable_array.dart:254)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:247:16)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #4      Future.Future.sync (dart:async/future.dart:168)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #5      Db.open (package:mongo_dart/src/database/db.dart:238:16)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #6      MongoHistorianAdapter.getDatabase.<getDatabase_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///C:/dsa/dglux-server/dslinks/MongoDB/bin/run.dart:41:16)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #8      _rootRun (dart:async/zone.dart:946)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #9      _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #10     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #12     _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #13     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #14     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-02-16 12:48:44.059125] [SEVERE][DSA] #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:47.130071] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:47.130071] 
[2019-02-16 12:48:47.130071] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62451
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:47.130071] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:49.063702] [SEVERE][DSA] Failed to connect to database for /t
[2019-02-16 12:48:49.063702] [SEVERE][DSA] MongoDart Error: Invalid scheme in uri: /downstream/Weather/Aguascalientes-4019233/Temperature 
[2019-02-16 12:48:49.063702] [SEVERE][DSA] #0      Db._parseUri (package:mongo_dart/src/database/db.dart:150:7)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:248:42)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #2      List.forEach (dart:core-patch/growable_array.dart:254)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:247:16)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #4      Future.Future.sync (dart:async/future.dart:168)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #5      Db.open (package:mongo_dart/src/database/db.dart:238:16)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #6      MongoHistorianAdapter.getDatabase.<getDatabase_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///C:/dsa/dglux-server/dslinks/MongoDB/bin/run.dart:41:16)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #8      _rootRun (dart:async/zone.dart:946)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #9      _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #10     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #12     _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #13     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #14     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-02-16 12:48:49.065701] [SEVERE][DSA] #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-02-16 12:48:53.134496] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:53.135496] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:53.135496] 
[2019-02-16 12:48:53.135496] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62455
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:53.135496] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] Failed to connect to database for /t
[2019-02-16 12:48:54.069844] [SEVERE][DSA] MongoDart Error: Invalid scheme in uri: /downstream/Weather/Aguascalientes-4019233/Temperature 
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #0      Db._parseUri (package:mongo_dart/src/database/db.dart:150:7)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:248:42)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #2      List.forEach (dart:core-patch/growable_array.dart:254)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:247:16)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #4      Future.Future.sync (dart:async/future.dart:168)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #5      Db.open (package:mongo_dart/src/database/db.dart:238:16)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #6      MongoHistorianAdapter.getDatabase.<getDatabase_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///C:/dsa/dglux-server/dslinks/MongoDB/bin/run.dart:41:16)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #8      _rootRun (dart:async/zone.dart:946)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #9      _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #10     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #12     _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #13     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #14     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-02-16 12:48:54.069844] [SEVERE][DSA] #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-02-16 12:48:59.075376] [SEVERE][DSA] Failed to connect to database for /t
[2019-02-16 12:48:59.075376] [SEVERE][DSA] MongoDart Error: Invalid scheme in uri: /downstream/Weather/Aguascalientes-4019233/Temperature 
[2019-02-16 12:48:59.075376] [SEVERE][DSA] #0      Db._parseUri (package:mongo_dart/src/database/db.dart:150:7)
[2019-02-16 12:48:59.075376] [SEVERE][DSA] #1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:248:42)
[2019-02-16 12:48:59.075376] [SEVERE][DSA] #2      List.forEach (dart:core-patch/growable_array.dart:254)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:247:16)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #4      Future.Future.sync (dart:async/future.dart:168)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #5      Db.open (package:mongo_dart/src/database/db.dart:238:16)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #6      MongoHistorianAdapter.getDatabase.<getDatabase_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (file:///C:/dsa/dglux-server/dslinks/MongoDB/bin/run.dart:41:16)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #7      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #8      _rootRun (dart:async/zone.dart:946)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #9      _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #10     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #12     _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #13     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #14     _CustomZone.runGuarded (dart:async/zone.dart:724)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[2019-02-16 12:48:59.077376] [SEVERE][DSA] #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] Failed to connect to database for /Temperatura
[2019-02-16 12:48:59.139336] [SEVERE][DSA] SocketException: OS Error: El equipo remoto rechazó la conexión de red.
[2019-02-16 12:48:59.139336] 
[2019-02-16 12:48:59.139336] [SEVERE][DSA] , errno = 1225, address = 127.0.0.1, port = 62456
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #2      _rootRunBinary (dart:async/zone.dart:970)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #3      _CustomZone.runBinary (dart:async/zone.dart:849)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #4      _FutureListener.handleError (dart:async/future_impl.dart:146)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #6      _Future._propagateToListeners (dart:async/future_impl.dart:671)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #7      _Future._completeError (dart:async/future_impl.dart:485)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #9      _rootRun (dart:async/zone.dart:950)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #10     _CustomZone.run (dart:async/zone.dart:826)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:753)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[2019-02-16 12:48:59.139336] [SEVERE][DSA] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[2019-02-16 12:49:01.194088] == Exited with status 1 ==
[2019-02-16 12:49:01.194088] == Exited with status 1 ==
[2019-02-16 12:49:01.194088] == Exited with status 1 ==
